// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// eResC
arma::vec eResC(arma::vec const Time, arma::vec const censor, arma::vec const wgt);
RcppExport SEXP _aftgee_eResC(SEXP TimeSEXP, SEXP censorSEXP, SEXP wgtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< arma::vec const >::type Time(TimeSEXP);
    Rcpp::traits::input_parameter< arma::vec const >::type censor(censorSEXP);
    Rcpp::traits::input_parameter< arma::vec const >::type wgt(wgtSEXP);
    rcpp_result_gen = Rcpp::wrap(eResC(Time, censor, wgt));
    return rcpp_result_gen;
END_RCPP
}
// eResC2
Rcpp::List eResC2(arma::vec const Time, arma::vec const censor, arma::vec const wgt);
RcppExport SEXP _aftgee_eResC2(SEXP TimeSEXP, SEXP censorSEXP, SEXP wgtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< arma::vec const >::type Time(TimeSEXP);
    Rcpp::traits::input_parameter< arma::vec const >::type censor(censorSEXP);
    Rcpp::traits::input_parameter< arma::vec const >::type wgt(wgtSEXP);
    rcpp_result_gen = Rcpp::wrap(eResC2(Time, censor, wgt));
    return rcpp_result_gen;
END_RCPP
}
// gee
Rcpp::List gee(arma::vec y, arma::mat X, arma::vec b0, arma::vec nt, arma::vec w, std::string corstr, double tol, int maxit);
RcppExport SEXP _aftgee_gee(SEXP ySEXP, SEXP XSEXP, SEXP b0SEXP, SEXP ntSEXP, SEXP wSEXP, SEXP corstrSEXP, SEXP tolSEXP, SEXP maxitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type nt(ntSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< std::string >::type corstr(corstrSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    rcpp_result_gen = Rcpp::wrap(gee(y, X, b0, nt, w, corstr, tol, maxit));
    return rcpp_result_gen;
END_RCPP
}
// est_No_Margin
Rcpp::List est_No_Margin(arma::vec y, arma::mat X, arma::vec D, arma::vec b0, arma::vec nt, arma::vec w, std::string corstr, double tol, int maxit);
RcppExport SEXP _aftgee_est_No_Margin(SEXP ySEXP, SEXP XSEXP, SEXP DSEXP, SEXP b0SEXP, SEXP ntSEXP, SEXP wSEXP, SEXP corstrSEXP, SEXP tolSEXP, SEXP maxitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type nt(ntSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< std::string >::type corstr(corstrSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    rcpp_result_gen = Rcpp::wrap(est_No_Margin(y, X, D, b0, nt, w, corstr, tol, maxit));
    return rcpp_result_gen;
END_RCPP
}
// resampling_No_Margin
arma::mat resampling_No_Margin(arma::vec y, arma::mat X, arma::vec D, arma::vec b0, arma::vec nt, arma::vec w, std::string corstr, int B, double tol, int maxit);
RcppExport SEXP _aftgee_resampling_No_Margin(SEXP ySEXP, SEXP XSEXP, SEXP DSEXP, SEXP b0SEXP, SEXP ntSEXP, SEXP wSEXP, SEXP corstrSEXP, SEXP BSEXP, SEXP tolSEXP, SEXP maxitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type nt(ntSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< std::string >::type corstr(corstrSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    rcpp_result_gen = Rcpp::wrap(resampling_No_Margin(y, X, D, b0, nt, w, corstr, B, tol, maxit));
    return rcpp_result_gen;
END_RCPP
}
// getSuv
arma::vec getSuv(arma::vec Time, arma::vec censor, arma::vec wgt);
RcppExport SEXP _aftgee_getSuv(SEXP TimeSEXP, SEXP censorSEXP, SEXP wgtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Time(TimeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type censor(censorSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type wgt(wgtSEXP);
    rcpp_result_gen = Rcpp::wrap(getSuv(Time, censor, wgt));
    return rcpp_result_gen;
END_RCPP
}
// log_ns_est
arma::vec log_ns_est(const arma::vec& a, const arma::mat& X, const arma::vec& D, const arma::vec& Y, const arma::vec& W, const arma::vec& gw);
RcppExport SEXP _aftgee_log_ns_est(SEXP aSEXP, SEXP XSEXP, SEXP DSEXP, SEXP YSEXP, SEXP WSEXP, SEXP gwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type D(DSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gw(gwSEXP);
    rcpp_result_gen = Rcpp::wrap(log_ns_est(a, X, D, Y, W, gw));
    return rcpp_result_gen;
END_RCPP
}
// gehan_s_est
arma::vec gehan_s_est(const arma::vec& a, const arma::mat& X, const arma::vec& D, const arma::vec& Y, const arma::vec& W, const int& nc, const arma::mat& sigma, const arma::vec& gw);
RcppExport SEXP _aftgee_gehan_s_est(SEXP aSEXP, SEXP XSEXP, SEXP DSEXP, SEXP YSEXP, SEXP WSEXP, SEXP ncSEXP, SEXP sigmaSEXP, SEXP gwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type D(DSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const int& >::type nc(ncSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gw(gwSEXP);
    rcpp_result_gen = Rcpp::wrap(gehan_s_est(a, X, D, Y, W, nc, sigma, gw));
    return rcpp_result_gen;
END_RCPP
}
// gehan_ns_est
arma::vec gehan_ns_est(const arma::vec& a, const arma::mat& X, const arma::vec& D, const arma::vec& Y, const arma::vec& W, const arma::vec& gw);
RcppExport SEXP _aftgee_gehan_ns_est(SEXP aSEXP, SEXP XSEXP, SEXP DSEXP, SEXP YSEXP, SEXP WSEXP, SEXP gwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type D(DSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gw(gwSEXP);
    rcpp_result_gen = Rcpp::wrap(gehan_ns_est(a, X, D, Y, W, gw));
    return rcpp_result_gen;
END_RCPP
}
// gehan_s_wt
arma::vec gehan_s_wt(const arma::vec& a, const arma::mat& X, const arma::vec& Y, const arma::vec& W, const int& nc, const arma::mat& sigma);
RcppExport SEXP _aftgee_gehan_s_wt(SEXP aSEXP, SEXP XSEXP, SEXP YSEXP, SEXP WSEXP, SEXP ncSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const int& >::type nc(ncSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(gehan_s_wt(a, X, Y, W, nc, sigma));
    return rcpp_result_gen;
END_RCPP
}
// gehan_ns_wt
arma::vec gehan_ns_wt(const arma::vec& a, const arma::mat& X, const arma::vec& Y, const arma::vec& W);
RcppExport SEXP _aftgee_gehan_ns_wt(SEXP aSEXP, SEXP XSEXP, SEXP YSEXP, SEXP WSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type W(WSEXP);
    rcpp_result_gen = Rcpp::wrap(gehan_ns_wt(a, X, Y, W));
    return rcpp_result_gen;
END_RCPP
}
// log_s_est
arma::vec log_s_est(const arma::vec& a, const arma::mat& X, const arma::vec& D, const arma::vec& Y, const arma::vec& W, const int& nc, const arma::mat& sigma, const arma::vec& gw);
RcppExport SEXP _aftgee_log_s_est(SEXP aSEXP, SEXP XSEXP, SEXP DSEXP, SEXP YSEXP, SEXP WSEXP, SEXP ncSEXP, SEXP sigmaSEXP, SEXP gwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type D(DSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const int& >::type nc(ncSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gw(gwSEXP);
    rcpp_result_gen = Rcpp::wrap(log_s_est(a, X, D, Y, W, nc, sigma, gw));
    return rcpp_result_gen;
END_RCPP
}
