# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @noRd
getSuv <- function(Time, censor, wgt) {
    .Call(`_aftgee_getSuv`, Time, censor, wgt)
}

#' @noRd
log_ns_est <- function(a, X, D, Y, W, gw) {
    .Call(`_aftgee_log_ns_est`, a, X, D, Y, W, gw)
}

gehan_s_est <- function(a, X, D, Y, W, nc, sigma, gw) {
    .Call(`_aftgee_gehan_s_est`, a, X, D, Y, W, nc, sigma, gw)
}

#' @noRd
gehan_ns_est <- function(a, X, D, Y, W, gw) {
    .Call(`_aftgee_gehan_ns_est`, a, X, D, Y, W, gw)
}

#' @noRd
gehan_s_wt <- function(a, X, Y, W, nc, sigma) {
    .Call(`_aftgee_gehan_s_wt`, a, X, Y, W, nc, sigma)
}

gehan_ns_wt <- function(a, X, Y, W) {
    .Call(`_aftgee_gehan_ns_wt`, a, X, Y, W)
}

log_s_est <- function(a, X, D, Y, W, nc, sigma, gw) {
    .Call(`_aftgee_log_s_est`, a, X, D, Y, W, nc, sigma, gw)
}

